### ISSUE TITLE
Regarding the Extraction of CCA as in 3.1

### ISSUE THREAD

**Issue by aristosp** [ankitapasad/layerwise-analysis#9]
Following the guide provided and trying to adapt it to AV-HuBERT, I've hit a roadblock, regarding the name of the model. I adapted it to fit previous usage of the variable $model_name but the when trying to run the script get_cca_scores.sh 
```
model_name=avhubert
data_sample=1
exp_name=cca-mel
span=frame
layer_num=4
bash scripts/get_cca_scores.sh $model_name $data_sample $exp_name $span /home/aristosp/av_hubert/test $layer_num
```

the output is:
```
Evaluating layer T4 for cca-mel
True
True
Traceback (most recent call last):
  File "codes/tools/get_scores.py", line 537, in <module>
    fire.Fire(
  File "/home/aristosp/anaconda3/envs/avhubert/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/aristosp/anaconda3/envs/avhubert/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/aristosp/anaconda3/envs/avhubert/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "codes/tools/get_scores.py", line 442, in evaluate_cca
    cca_obj = getCCA(
  File "codes/tools/get_scores.py", line 51, in __init__
    self.num_conv_layers = LAYER_CNT[model_name]["local"]
KeyError: 'avhubert'
```
Which implies there is something wrong with the model_name variable, even though it works with previous use of this variable.

**Comment by aristosp** [comment]
Update: Sometimes inside your code you use the name avhubert, others the name avhubert_small_lrs3_vc2, which causes a discrepancy between the codes that someone may need to run
